### ISSUE TITLE
Openstreetmap display problem

### ISSUE THREAD

**Issue by dr1ss** [albar965/littlenavmap#856] opened 2022-02-17 16:36 UTC
Hello, there is a problem with the map display (see screenshot)
Apparently due to changes from OSM : 
https://phabricator.wikimedia.org/T187601#7642399

- Windows 11 64 Bit
- Microsoft  Flight Simulator 
- Little Navmap 2.6.17
 
![image](https://user-images.githubusercontent.com/537914/154526966-941f8d01-7b16-47c0-8aff-e9f5a8b11a38.png)

**Comment by albar965** [comment] 2022-02-17 18:39
Duplicate of #849, #844, #839 and #838 :slightly_smiling_face: 

See Avsim pinned topic https://www.avsim.com/forums/topic/613903-map-display-issues-with-openstreetmap-and-other-maps/?tab=comments#comment-4709913
or FAQ: https://albar965.github.io/littlenavmap-faq.html#hillshadingissues

You have to disable hillshading in the LNM menu "View" or use another map theme like OpenTopoMap or StamenTerrain to fix this.

**Closed by albar965** 2022-02-17 18:39 UTC

**Comment by dr1ss** [comment] 2022-02-19 22:48
Oh sorry about the duplicate.. disabling Hillshading fixed the issue thank you
