### ISSUE TITLE
Different colors denoting different altitudes for flown path in logbook

### ISSUE THREAD

**Issue by Trigonoculus** [albar965/littlenavmap#738] opened 2021-07-15 19:05 UTC
Hi - I would like to propose a feature. Since I noticed that the flight path recorded includes the altitude, I think having different colors for different altitudes may be a good idea to highlight them. As an example, below is a screenshot from Flightradar24:

![image](https://user-images.githubusercontent.com/20501245/125841929-d5195892-b699-4e5a-85ac-0b4ad9225854.png)

I did a flight a few days ago, which I had to make a diversion to an alternate airport. Showing the altitude change would be great.

![image](https://user-images.githubusercontent.com/20501245/125843154-59ae5822-9c03-4411-8c41-2c45db074bb1.png)

Thank you for making this great tool, have a wonderful day.

**Comment by albar965** [comment] 2021-07-20 18:23
Duplicate of #97. Just moved #97 to 2.8 milestone but this will take some time, sorry.
Alex

**Closed by albar965** 2021-07-20 18:23 UTC

**Comment by Trigonoculus** [comment] 2021-07-20 18:45
Ah, seems like I missed that one while searching. Please take all the time you need, appreciate it.

Trig
