### ISSUE TITLE
UserdataIcons translated, but still English text

### ISSUE THREAD

**Issue by tonghuix** [albar965/littlenavmap#631] opened 2021-04-03 19:36 UTC
Just finished all Chinese translation, and tesing, I found this bug. 

I tried other languages' translations, like Franch, Itanlian etc, all have the same issue.

**Comment by albar965** [comment] 2021-04-03 21:29
Known issue. Not so easy since the icon names are used in English form for search and more.
Duplicate of  #258 which I just assigned to the 2.8 milestone. Closing, therefore.

**Closed by albar965** 2021-04-03 21:29 UTC
