### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Gatner-Dev** [albar965/littlenavmap#839] opened 2022-01-22 22:58 UTC
Hello i have problem with little navmap .. when i zoom in its sayin "contact user TheDj" if you want to maintain OSMdb and/or the wmflabs' OSM tiles server. Any ideas ? 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/66118947/150658064-6b745cf8-91d4-4bd6-b020-1454c786ebdf.png">

**Comment by albar965** [comment] 2022-01-23 11:55
Duplicate of #838 . You can continue the discussion right there.

See also here for more information: https://www.avsim.com/forums/topic/613903-map-display-issues-with-openstreetmap-and-other-maps/?tab=comments#comment-4709913

To put it short: Disable hillshading in the LNM menu "View" or use another map theme like OpenTopoMap or StamenTerrain.

Alex

**Closed by albar965** 2022-01-23 11:55 UTC
