### ISSUE TITLE
Aerosoft CRJ-700/900 route import issue

### ISSUE THREAD

**Issue by fleurenf55** [albar965/littlenavmap#475] opened 2019-11-26 06:00 UTC
Hi Alex,
I’ve purchased the Aerosoft CRJ 700/900X for FSX and have an issue with importing a Flightplan created with Little NavMap. Both the CRJ Database and Little Navmap have the latest Airac.
The .flp created works great with the Aerosoft Airbus series but the format is not recognised with the CRJ.
It when imported, it will show the departure and arrival airports but not the route (ie waypoints etc).
Can you advise on this?

**Comment by albar965** [comment] 2019-11-26 15:54
Hi,
this is probably a duplicate for #184.
The export format for the newer Aerosoft aircraft has changed and needs a lot more information (see PDF file linked in #184).
Can you attach an example how it should look? There are probably tutorial flightplans or a description in the aircraft manual.
Alex

**Comment by fleurenf55** [comment] 2019-11-26 22:39
Hi Alex,
The attached has been created via the FMC in the CRJ-900 using the route provided by LittleNavMap.

[EKCHEGBB.zip](https://github.com/albar965/littlenavmap/files/3894257/EKCHEGBB.zip)

Kind regards,
Fred

**Comment by albar965** [comment] 2019-11-27 12:46
Thanks for the example. It contains all the data which is not yet provided by LNM. 
#184 will fix this.
I'm closing this issue since it is a duplicate of #184.
Alex

**Closed by albar965** 2019-11-27 12:46 UTC
