### ISSUE TITLE
SIDs and STARS from MSFS

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [albar965/littlenavmap#643] opened 2021-05-05 12:07 UTC
After loading the scene library from the correct MSFS folder, selecting MSFS2020 in the scenery library tab, and setting LNM not to use the navigraph AIRAC cycle, the only available procedures for airports are approaches and there are no SIDs and STARs. Would it be possible to import SIDs and STARs from msfs ? Or is something wrong on my end ?

**Comment by albar965** [comment] 2021-05-05 12:13
This is a known issue mentioned in the manual and FAQ. It will be fixed with the next release.

Read here
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/SCENERY.html#microsoft-flight-simulator-2020-airports-and-navdata
and here
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/NAVDATA.html
about the different navigation database modes in the scenery library menu.

Duplicate of #555 . Closing.
Alex

**Closed by albar965** 2021-05-05 12:13 UTC
