### ISSUE TITLE
A double button to display or hide AI and Multiplayer players.

### ISSUE THREAD

**Issue by Patbest** [albar965/littlenavmap#189] opened 2017-12-16 20:29 UTC
Hi Patrick, please delete the template content next time. :smile: 
I have to check whether this information is available or not for all the simulators. As far as I remember there is no noticeable difference in data for multiplayer and AI.

**Comment by albar965** [comment] 2022-03-06 13:08
Duplicate of #754

**Closed by albar965** 2022-03-06 13:08 UTC
Labels: enhancement, requested
