### ISSUE TITLE
Xplane 11 AI aircraft losing data labels

### ISSUE THREAD

**Issue by lenvdb** [albar965/littlenavmap#992] opened 2023-01-30 17:21 UTC
Version 1.0.33 and 1.0.34 Little Xpconnect are losing AI aircraft data labels when taking off or landing at airfields.
This is with using Xpilot version 2.0.0-beta.43.
Labels can be restored once the aircraft is airborne by disconnecting and reconnecting Xpilot.

This problem does not occur using Little Xpconnect 1.0.32.

Still love the program.

**Comment by albar965** [comment] 2023-01-30 19:20
LNM shows aircraft on ground only at deep zoom levels to avoid stuffing the airports.
Aircraft and/or labels will be hidden until zoomed close in. The aircraft on ground also have a gray outline.

albar965/littlexpconnect@2533a6641ef11fe0414fca5e2fdc1f6caeff03c0 might be the issue. But it probably also corrected the on-ground flag which results in disappearing aircraft and labels.  I tested this only with XP stock AI. Have to see.

**Comment by albar965** [comment] 2023-02-09 11:31
I cannot reproduce this with the stock AI. Maybe an issue in X-Pilot which does not inject the correct on-ground status.

I'll check if I can add a workaround since many third party tools do not get this right.

**Comment by lenvdb** [comment] 2023-02-09 12:31
Thanks for that.One of my colleagues also had a problem seeing AI aircraft on Xplane 11. By disconnecting and reconnecting Xpilot all the AI aircrafts became visible. Ses to point to Xpilot.RegardsLenOn 9 Feb 2023 11:31, Alexander Barthel ***@***.***> wrote:
I cannot reproduce this with the stock AI. Maybe an issue in X-Pilot which does not inject the correct on-ground status.
I'll check if I can add a workaround since many third party tools do not get this right.

**Comment by albar965** [comment] 2023-02-09 15:31
> Thanks for that.One of my colleagues also had a problem seeing AI aircraft on Xplane 11. By disconnecting and reconnecting Xpilot all the AI aircrafts became visible.

I would not wonder if X-Pilot overwrites the AI information.

**Comment by albar965** [comment] 2023-02-22 20:21
Most likely fixed with the workaround 5475768c2a30e1be890678eda93ed6182fd959a5

**Closed by albar965** 2023-02-22 20:21 UTC
Labels: bug
