### ISSUE TITLE
Date of weather inconsistency

### ISSUE THREAD

**Issue by 737simpilot** [albar965/littlenavmap#324] opened 2018-12-01 07:11 UTC
![1](https://user-images.githubusercontent.com/16517998/49325333-c5f6f700-f4fd-11e8-92bf-6b907ab2df1a.jpg)
Using Active Sky 2016, LittleNavMap version 2.0.3 and FSX Deluxe boxed in Windows 7 64. 

For some reason I'm seeing in LittleNavMap under weather that the date goes back a month. But it looks like the weather is accurate for the Sim and in real life. 

Now when I exited the simulator the date that was in red is gone and Dec 1st shows up instead of Nov 1st.

**Comment by 737simpilot** [comment] 2018-12-05 08:32
Hi. Using version 2.2.2.rc2. Still have the same issue shown in the pic. However, relaunching LittleNavMap after my Sim flight the problem is not there. 



![hujtyjt](https://user-images.githubusercontent.com/16517998/49500295-99a8e680-f82d-11e8-98d3-53a619a4c921.jpg)

**Comment by albar965** [comment] 2018-12-05 10:23
Was a "activeflightplanwx.txt" around that delivered old weather overriding "current_wx_snapshot.txt"?
Can you send me the LNM log from such a situation?
I cannot reproduce this and I'm a bit at a loss here. 
Alex

**Comment by 737simpilot** [comment] 2018-12-06 08:37
Attached are two sets of files in the 7z. Before I flew in the Sim, and after I flew in the Sim.[logs.zip](https://github.com/albar965/littlenavmap/files/2652282/logs.zip)

**Comment by albar965** [comment] 2018-12-08 19:56
Thank you for the log files. I see nothing wrong there so far.
Try this version here: https://www.magentacloud.de/lnk/c4lxUjJ7

If that does not work set `WeatherDebug=true` in the `C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel\little_navmap.ini` file, run a session where the error appears and send me the logs.
```
[Options]
...
WeatherDebug=true
...
```
Not sure if I can fix this for the release.

Alex

**Comment by albar965** [comment] 2018-12-11 15:22
Does this still occur with the 2.2.2 release?
I had similar problems with other files (X-Plane weather) but these are fixed as far as I can see.
Alex

**Comment by 737simpilot** [comment] 2018-12-18 05:08
Hi. It seems like it is working thus far in 2.2.2. I haven't seen the problem again.

**Comment by albar965** [comment] 2018-12-18 15:57
Thanks. Great. 
This is (hopefully was) one of the hard to reproduce bugs that kept coming back to me. 
Feel free to close the issue if you don't see it again. You can always reopen it if the problem shows up again.
Alex

**Comment by 737simpilot** [comment] 2018-12-18 21:37
I'll fly in the Sim a few more times and make sure the issue is definitely gone, which I'm sure it is and then I'll go ahead and close the ticket. 

Many thanks, and thanks for a great program. I use it on my second screen all the time and it's been wonderful. 

Merry Christmas and happy holidays.

**Comment by albar965** [comment] 2018-12-18 22:18
Wish you happy holidays too!
Alex

**Closed** 2018-12-23 09:04 UTC

**Comment by Gulliver54** [comment] 2018-12-23 13:38
I never experienced this behaviour with ASP4 / P3DV4 Window7

**Comment by albar965** [comment] 2018-12-23 13:41
I experienced it (different file but same code) with the X-Plane weather file as mentioned above. Hope it is fixed for good.
Alex
