### ISSUE TITLE
Strange error after lnm db update

### ISSUE THREAD

**Issue by rippy65** [albar965/littlenavmap#910] opened 2022-08-19 17:16 UTC
Latest lnm build - tried to rebuild the db...getting this:

![image](https://user-images.githubusercontent.com/58223079/185672565-62284a64-d24d-4eee-963e-80c6465f7dbb.png)

**Comment by albar965** [comment] 2022-08-19 18:44
Did you build this yourself? Means you're ahead of 2.7.10.develop?
Or do you use the latest 2.6.19 or the public alpha 2.7.10.develop?

This was actually fixed with https://github.com/albar965/atools/commit/6b191edd2c58a17db509be843962362278990fc6

If you search through the log file you can see a message like (from another log):

```
[... INFO ]: Scenery path "F:\\FS\\Community\\pilots-airport-2nc0-mountain-air"
[... INFO ]: =P=== "9379 of 11465 (81 %) [1]" "pilots-2nc0-modelLib.BGL"
[... INFO ]: =P=== "9380 of 11465 (81 %) [1]" "2nc_Objects.bgl"
[... WARN ]: Waypoint at Pos(-176.336151,-85.865021,0.000000) ident WPNAME has no region
```

The problem is the scenery file above the warning (`2nc_Objects.bgl` here).

**Comment by rippy65** [comment] 2022-08-19 18:55
Latest 2.6.19. Will look into the log now.

**Comment by albar965** [comment] 2022-08-19 19:01
Thanks. I took note to merge this fix into the next 2.6.20. SU10 will break LNM anyway as far as I can see.

**Comment by rippy65** [comment] 2022-08-19 19:09
buggy *.bgl found, lnm error fixed. Thanks for pointing me in the right direction. Have a good evening + we!

**Comment by albar965** [comment] 2022-08-19 20:14
You're welcome. Have a nice one too!

**Comment by albar965** [comment] 2022-08-20 09:50
Closing now since it is fixed. Feel free to reopen if it appears again after the next LNM update.

**Closed by albar965** 2022-08-20 09:50 UTC
Labels: bug
