### ISSUE TITLE
Add-on Airport Not Found while rescanning datas from MSFS

### ISSUE THREAD

**Issue by cowreth** [albar965/littlenavmap#809] opened 2021-10-31 11:42 UTC
Hi Alex :)

**Intro**
Here's a bug that is not really important. It's okay, I can use an other gate.
But there may be a more important hidden bug in the indexation service, and this one could put light on it. Hence the report.
I'm not sure how I can dig more in this, but I'm willing to do a million tests if it can help ;)

**Bug Short Description**
Although an official scenery add some new gates, I can't see it in LNM.

**Installation**
Windows 10 64bits
MSFS (not steam) with SU6
LNM 2.6.17
AIRAC : MSFS Stock (& LNM Stock)
Scene Concerned : Airport scene of LFMT by France VFR
https://www.francevfr.com/product_aptlfmtmsfs.php

**Fix tried**
I've removed the whole database [1] then rebuilt the database in LNM, from scratch.

**Reproducing the bug**
- The stock version of MSFS for MSFS has a gate A3. 
- Few meters away on the east, there should be an A6 Gate.
- Buy and install the scenery in the MSFS instore.
- As an official package, this scenery will land in [2]
- Get into MSFS, world map : the new gate A6 is there, right a few meters on the east of A3.
- The gate is also present on SIA / AIP documentation : [search for "A6"]( https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_07_OCT_2021/FRANCE/AIRAC-2021-10-07/html/eAIP/FR-AD-2.LFMT-fr-FR.html) or [page 38 here](https://www.dircam.dsae.defense.gouv.fr/images/Stories/Doc/MIAC1/miac1_montpellier_lfmt.pdf)
- Rebuild the LNM database, with or without emptying it beforehand.
- The gate A6 is not visible in LNM

Cheers,
K.

[1] `C:\Users\[name]\AppData\Roaming\ABarthel\little_navmap_db\`
[2] `C:\Users\[user]\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\francevfr-airport-lfmt-montpellier`

**Comment by cowreth** [comment] 2021-10-31 12:09
Okay, ce bug là ne va probablement pas tenir la première enquête.

A creuser, je découvre que le fichier principal de l'add-on est un FSARCHIVE, le fameux format chiffré de MS/Asobo qui empêche les modifications. Et, le cas échéant, la lectures des données. Je pense que les BGL sont dans ce fichier, et que donc LNM n'y a pas accès lors de l'indexation.

A [priori](https://www.vfrnetwork.com/forums/index.php?/topic/18659-urgent-demande-de-confirmation-format-de-fichier-sc%C3%A8ne/&tab=comments#comment-236042), en achetant directement sur Simware, la _scenery_ serait venue en mode "zip à mettre dans le dossier Community", et donc probablement sans le FSArchive. 

Pour le même prix, on a donc sur le instore MSFS un fichier avec DRM qui empêche LNM de fonctionner correctement.

Alex, je te laisse fermer ce bug à convenance.

**Comment by albar965** [comment] 2021-11-01 11:16
Thanks for the detailed report.
Duplicate of #802 but I keep this too due to the detailed.

**Comment by albar965** [comment] 2021-11-01 12:12
I see. Encryption cannot be fixed. Please translate your answer the next time (https://www.deepl.com/translator).

> Okay, this bug probably won't last the first investigation.
>
> Digging around, I discover that the main file of the add-on is a FSARCHIVE, the famous MS/Asobo encrypted format that prevents modifications. And, if necessary, the reading of the data. I think that the BGLs are in this file, and that LNM does not have access to them during the indexing.
>
> If I had bought directly from Simware, the scenery would have come as a zip file to be put in the Community folder, and therefore probably without the FSArchive.
>
> For the same price, we have on the MSFS instore a file with DRM that prevents LNM from working properly.
>
> A Alex, I let you close this bug at your convenience.

**Closed by albar965** 2021-11-01 12:12 UTC

**Comment by cowreth** [comment] 2021-11-03 17:07
Wow. Sorry, I was so much in my tunnel that I forgot to answer in english :D :D
Gotta say sorry, and thanks for this wonderful piece of work LNM is ;)

Cheers,
K.

**Comment by albar965** [comment] 2021-11-03 17:09
No problem and thanks for the kind words. :upside_down_face: 
Alex
