### ISSUE TITLE
Month is wrong in weather information panel

### ISSUE THREAD

**Issue by tillbcrazy** [albar965/littlenavmap#583] opened 2020-10-25 04:36 UTC
The month is wrong in the date format of the weather information. All sources will list the wrong month. 

Littlenavmap version 2.6.2
Windows 10 64 bit version 2004

<img width="104" alt="Capture" src="https://user-images.githubusercontent.com/11842813/97099007-9be5db00-1627-11eb-9343-27a4731e6e42.PNG">

**Comment by albar965** [comment] 2020-10-25 11:20
I cannot reproduce this but this might be a timezone dependent issue. I see some potential issues in the code and will fix this.

**Comment by albar965** [comment] 2020-11-02 16:53
Hopefully fixed in the upcoming 2.6.3.beta

**Closed by albar965** 2020-11-02 16:53 UTC
Labels: bug

**Comment by tillbcrazy** [comment] 2020-11-02 19:52
Great! I'll let you know when you release it. I'm sorry I didn't reply earlier. I meant to tell you that my time zone is GMT -10 if that might help things.
