### ISSUE TITLE
Long Distance Route plotting issue

### ISSUE THREAD

**Issue by fleurenf55** [albar965/littlenavmap#476] opened 2019-12-02 21:51 UTC
Hi Alex,
I have an issue with trying to plot a route across the Atlantic Ocean.
The route I'm trying to create is from Amsterdam Schiphol EHAM to George Bush Intercontinental KIAH approx 4507nm. I get a message that it can't find the route. I'm assuming that LittleNavMap doesn't recognise or has the North Atlantic Tracks NAT included.

I note Issue #82 covers my query so no further action on my part is required. How far are you from including the Nat/PACOTS in V2.6?
Kind regards,
Fred

**Comment by albar965** [comment] 2019-12-03 15:30
Hi Fred,
this should be fixed with #466 and #82 . Both issues have priority for the next 2.6 since #82 is already lingering around for a long time and #466 should fix annoying problems with the airway system holes in Europe.
Work on these issues did not start yet. I spent a lot on the conversion of the user manuals since I had to get rid of Gitbook.
Closing since it is a duplicate of #82
Alex

**Closed by albar965** 2019-12-03 15:30 UTC
