### ISSUE TITLE
Getting told to contact a user on top of map

### ISSUE THREAD

**Issue by davidbuckleyni** [albar965/littlenavmap#844] opened 2022-01-30 20:19 UTC
Getting this in my map view

![image](https://user-images.githubusercontent.com/5619229/151716206-a1964208-c0ea-4c88-b408-e47d65aae03a.png)

**Comment by albar965** [comment] 2022-01-30 20:49
Duplicate of #838

See here for more information: https://www.avsim.com/forums/topic/613903-map-display-issues-with-openstreetmap-and-other-maps/?tab=comments#comment-4709913

You have to disable hillshading in the view menu to get rid of this.

**Closed by albar965** 2022-01-30 20:49 UTC
