### ISSUE TITLE
Airport procedures don't working after upgrade to Airac cycle 1909

### ISSUE THREAD

**Issue by lenwen** [albar965/littlenavmap#444] opened 2019-08-16 09:00 UTC
Airport has no procedures is showing on all airport I have tested. (around 100)
And I know that the airports have procedures. Have tested in 1908 version .and all is working in 1908. But not in 1909.

Is something wrong whit navigraph 1909 or is it something in Little navmap.

Version information from log:
[2019-08-16 10:35:56.660 default INFO ]: ================================================================================
[2019-08-16 10:35:56.661 default INFO ]: Starting "Little Navmap" version "2.2.4"
[2019-08-16 10:35:56.661 default INFO ]: Organization "ABarthel" domain "littlenavmap.org"
[2019-08-16 10:35:56.661 default INFO ]: Application file path "C:/Games/Little Navmap/littlenavmap.exe"
[2019-08-16 10:35:56.661 default INFO ]: Application dir path "C:/Games/Little Navmap"
[2019-08-16 10:35:56.661 default INFO ]: Application arguments ("C:\\Games\\Little Navmap\\littlenavmap.exe")
[2019-08-16 10:35:56.662 default INFO ]: Current working directory "C:/Games/Little Navmap"
[2019-08-16 10:35:56.662 default INFO ]: Library paths ("C:/Games/Little Navmap/plugins", "C:/Games/Little Navmap")
[2019-08-16 10:35:56.662 default INFO ]: Log file 1 "C:/Users/xxxxxxxxx/AppData/Local/Temp/abarthel-little_navmap.log"
[2019-08-16 10:35:56.662 default INFO ]: Default text codec "System"
[2019-08-16 10:35:56.662 default INFO ]: Locale name "sv"
[2019-08-16 10:35:56.663 default INFO ]: UI languages ("sv-SE", "en-US")
[2019-08-16 10:35:56.663 default INFO ]: ABI "i386-little_endian-ilp32"
[2019-08-16 10:35:56.663 default INFO ]: build CPU arch "i386" current "x86_64"
[2019-08-16 10:35:56.663 default INFO ]: kernel "winnt" version "10.0.18362"
[2019-08-16 10:35:56.663 default INFO ]: product name "Windows 10 (10.0)" type "windows" version "10"
[2019-08-16 10:35:56.663 default INFO ]: Qt version 5.9.5
[2019-08-16 10:35:56.663 default INFO ]: Windows version 192
[2019-08-16 10:35:56.663 default INFO ]: atools revision 5ae9b03 Little Navmap revision 48a57304

**Comment by albar965** [comment] 2019-08-16 09:02
Thanks but it was already reported. Duplicate of #443 
Alex

**Closed by albar965** 2019-08-16 09:02 UTC
Labels: duplicate

**Comment by albar965** [comment] 2019-08-16 12:40
Fixed: https://www.avsim.com/forums/topic/558288-latest-1909-nav-data-ksfo-proceedures-wrong/
Alex
