### ISSUE TITLE
VR?

### ISSUE THREAD

**Issue by icecold951** [albar965/littlenavmap#621] opened 2021-03-21 00:28 UTC
Not exactly an issue, but would be super amazing. For one, this appears to use the sim map, incorrect markings and all. Other maps that work in sim use the real world maps for airports and such. 
I love this for that, but hate taking my headset off each time to look at it.

**Comment by albar965** [comment] 2021-03-22 10:59
I have no idea how to do this. 

As far as I know there are third party tools which allow to show the LNM or any application window in VR. I've seen this at least for P3D.

Maybe it would make sense to improve the web interface and use this instead.

**Comment by albar965** [comment] 2022-02-05 11:35
Duplicate of #747

**Closed by albar965** 2022-02-05 11:35 UTC
