### ISSUE TITLE
Problems with rendering approach

### ISSUE THREAD

**Issue by www2000** [albar965/littlenavmap#252] opened 2018-06-19 23:11 UTC
Hi i wand to report some problems with rendering miss approach
![bugreport](https://user-images.githubusercontent.com/721977/41628107-5b1cd6f8-7423-11e8-86cc-985a5e74645a.png)
In this image shows a screen shot of the LDA T RWY 22 approach for "Tokyo (Haneda) int" airport (ICAO: RJTT).
The red and green line is the over the screen shot show the approach on the map.
Where the red line is the normal approach route where the green line is the miss approach is the miss approach.

edit: I think the stage machine for the Missed approach routes need to ignore the runway fix.

**Comment by albar965** [comment] 2018-06-20 09:36
The problem is that the missed is drawn from the wrong point. As you show in the image it should be drawn from the MAP.
There are more problems in drawing approaches which can probably never be fixed. See #205 

This one should be fixed. I'll have a look at this for 2.2.
Alex

**Comment by albar965** [comment] 2018-07-23 11:57
Fixed so far. Did spot checks for various approaches.

![grafik](https://user-images.githubusercontent.com/15254956/43074162-d858bab2-8e6b-11e8-9079-82c42f583bce.png)

**Closed by albar965** 2018-07-23 11:57 UTC
Labels: bug, in progress
