### ISSUE TITLE
Oversized map in Webserver view

### ISSUE THREAD

**Issue by AndLindemann** [albar965/littlenavmap#547] opened 2020-08-29 10:57 UTC
Running LNM on MacOS 10.15, connected to MSFS 2020 on my Windows PC over LNConnect.
When activating the webserver in LNM and viewing the map via the webpage, the map is massively oversized to the point that it would cover 2-3 times the size of my screen, so that it is practically impossible to view.

As you can see on the screenshots, there is scrollbars at the borders of the website indicating that the screen covers only maybe 1/4th of the actual map display size.
The screenshot is taken from Safari on MacOS, but it is the same when I open the map on my Windows PC on an ultra-wide monitor which should have plenty of screen estate. As well the displayed map only is about 1/4th of the actual map size, so you'd have to scroll a lot.
Is this intended? I wasn't able to find anything in the docs regarding possibilities to resize the map display on the webserver page.

MacOS screenshot (Safari):
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/4157845/91635236-106d1680-e9f7-11ea-88e2-8dce1dea95d7.png">

Windows PC Screenshot (Firefox):
![Windows Screenshot](https://user-images.githubusercontent.com/4157845/91635274-57f3a280-e9f7-11ea-80cb-2a471fcd46f4.png)

**Comment by albar965** [comment] 2020-08-29 12:03
Thanks for the report. Will check for the next release but gimme some time.

**Comment by albar965** [comment] 2020-09-09 21:55
Sorry. I cannot reproduce this no matter which combination of OS and browser I use. The scrollbar shows up and disappears after a second on some browsers. On others it does not even show up.
![grafik](https://user-images.githubusercontent.com/15254956/92659060-ee796b00-f2f7-11ea-819e-1afe7fa89fac.png)

**Comment by kmuto** [comment] 2020-12-03 14:19
I have same problem.

Host: Little Navmap 2.6.4.beta on Windows 10
Client1: Google Chrome and Edge on same host, 4K display
Client2: Google Chrome and Edge on macOS 10.15, Retina display

Menu bar and zoom button are OK, but only map is displayed oversize (double size).
I suspect this problem is caused by the scaling setting.

Attached file:
 - 100p.png, 100p-inspect.png : on Windows, display scaling 100%. map image is loaded as 958x708 pixels
 - 150p.png, 150p-inspect.png : on Windows, display scaling 150%. map image is loaded as 1920x1416 pixels (expected size is 960x708)
- retina-inspect.png: on macOS, retina display. map image is loaded as 1960x996 pixels (expected size is 980x498)

When I modify width/height in mapimage parameter on Chrome DevTools for test, it seems be changed to correct size.
 
[littlenavmap-20201203T140913Z-001.zip](https://github.com/albar965/littlenavmap/files/5636569/littlenavmap-20201203T140913Z-001.zip)

**Comment by kmuto** [comment] 2020-12-04 01:14
It depends on host side scaling settng, not client side.
When I chose "scaling 100%" on Windows host and launched littlenavmap, all clients showed correctly. Doing with 125% is OK also.
When I chose "scaling 150%", oversize raised again.

**Comment by albar965** [comment] 2020-12-04 10:32
Good hint with the host side scaling.
Try to toggle `Enable high DPI monitor support` on options page `Display and Text`. Maybe this helps.

**Comment by kmuto** [comment] 2020-12-04 13:05
> Good hint with the host side scaling.
> Try to toggle `Enable high DPI monitor support` on options page `Display and Text`. Maybe this helps.

Yeah, it works for my environment by disabling this option. Thanks!

**Comment by albar965** [comment] 2021-09-03 20:01
Should be fixed with all the new web UI code.

**Closed by albar965** 2021-09-03 20:01 UTC
Labels: bug, web

**Comment by u-an-i** [comment] 2021-09-03 20:04
yes, this issue was made possible to alleviate with https://github.com/albar965/littlenavmap/pull/648 (now the "legacy" ui) and is no issue in the new web ui.
