### ISSUE TITLE
Custom altitude for waypoints

### ISSUE THREAD

**Issue by Gfurst** [albar965/littlenavmap#587] opened 2020-10-30 23:09 UTC
I'd like to both setable altitude for custom waypoints on the flight plan, as well as height limitations for custom user made fixes. This not only should be good to have a more accurate representation of the flight plan regime and vertical profile (as well as ground elevation awareness), but also to comply to restriction is some specific air spaces.

For example, I've mapped the custom waypoints according to real world VFR references used in visual area charts, these are corridor likes with several different altitude restriction (due to regional constraints, nearby IFR traffic routes), or for example when you have descent ahead of time to make for circuit height.

**Comment by albar965** [comment] 2020-10-31 11:34
Duplicate of #166
Very unlikely to happen due to high complexity.

**Closed by albar965** 2020-10-31 11:34 UTC
