### ISSUE TITLE
Little Navmap Installer

### ISSUE THREAD

**Issue by harveywalker500** [albar965/littlenavmap#993] opened 2023-02-04 14:24 UTC
Hi everyone, 

I have used Advanced Installer to create a .msi package to allow Little Navmap to be installed like a normal windows application. Once complete, it creates a shortcut to the windows directory like a normal installer. I'm more then happy to share this with the community if it would be allowed. For the readme and the license to be read by the installer, I've converted them to .rtf files through an online tool. I think it would be a great asset for Little Navmap to be a dedicated installer, as it would simplify the file structure by installing it in a single location within the windows program files directory.

I can't attach an .msi file, but I would love some insight on how I could improve it. If you would like to give it a go, feel free to message me and I will happily give you the installer.

Thanks again!

**Comment by albar965** [comment] 2023-02-04 16:54
Thank you. Appreciate it. 

Two questions:
- Is there a free version of the installer for open source programs? 
- Is there a way to provide scripts or configuration files so I can also create the builds my self?

Maybe the Qt Installer Framework is an option: https://doc.qt.io/qtinstallerframework/index.html

Alex

**Comment by decrisp1252** [comment] 2023-02-06 12:21
> Another free and open source installer: [Nullsoft Scriptable Install System](https://sourceforge.net/projects/nsis/)

Thanks Alex; I'm playing around with NSIS now. It's very fun!

Just a quick question: I'm assuming Little Navmap doesn't require access to the registry?

**Comment by albar965** [comment] 2023-02-06 12:51
> Just a quick question: I'm assuming Little Navmap doesn't require access to the registry?

No. Only to detect FSX or P3D but it does not need any special entries for itself.
The created files and databases are explained here: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/FILES.html Just in case you make full deinstall option (including settings and databases). 

If a license is needed: This is included with LNM file `LICENSE.txt`

You might also want to create a start menu entry for Little Navconnect (included in the download).

Alex

**Comment by decrisp1252** [comment] 2023-02-07 21:21
Hi, I've managed to create a basic installer for NSIS. It is basic in terms of the UI, but the functionality is there. It installs the files in \AppData\Local and creates Little Navmap and Little Navconnect in a folder for the start menu.

**Before you compile the code, you need to change the directory marked below as "HERE".**

Feel free to let me know if you have any thoughts.

It won't let me put it as a file; the code is below.

```
;NSIS Modern User Interface
;Start Menu Folder Selection Example Script
;Written by Joost Verburg

;--------------------------------
;Include Modern UI

  !include "MUI2.nsh"

;--------------------------------
;General

  ;Name and file
  Name "Little Navmap"
  OutFile "Install Little Navmap.exe"
  Unicode True

  ;Default installation folder
  InstallDir "$LOCALAPPDATA\Little Navmap"

  ;Request application privileges for Windows
  RequestExecutionLevel user

;--------------------------------
;Variables

  Var StartMenuFolder

;--------------------------------
;Interface Settings

  !define MUI_ABORTWARNING

;--------------------------------
;Pages

  !insertmacro MUI_PAGE_LICENSE "F:\NSIS\Little Navmap\LICENSE.txt"
  !insertmacro MUI_PAGE_COMPONENTS
  !insertmacro MUI_PAGE_DIRECTORY
  
  !insertmacro MUI_PAGE_STARTMENU Application $StartMenuFolder
  
  !insertmacro MUI_PAGE_INSTFILES
  
  !insertmacro MUI_UNPAGE_CONFIRM
  !insertmacro MUI_UNPAGE_INSTFILES

;--------------------------------
;Languages
 
  !insertmacro MUI_LANGUAGE "English"

;--------------------------------
;Installer Sections

Section "Little Navmap" SecDummy

  SetOutPath "$INSTDIR"
  
  ; ---------- HERE ----------
  File /r "F:\NSIS\Little Navmap\*"
  ; ---------- HERE ----------
  
  ;Create uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"
  
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
    
    ;Create shortcuts
	CreateDirectory "$SMPROGRAMS\Little Navmap"
    CreateShortcut "$SMPROGRAMS\Little Navmap\Little Navmap.lnk" "$INSTDIR\littlenavmap.exe"
	CreateShortcut "$SMPROGRAMS\Little Navmap\Little Navconnect.lnk" "$INSTDIR\Little Navconnect\littlenavconnect.exe"
    CreateShortcut "$SMPROGRAMS\Little Navmap\Uninstall Little Navmap.lnk" "$INSTDIR\uninstall.exe"
  
  !insertmacro MUI_STARTMENU_WRITE_END

SectionEnd

;--------------------------------
;Descriptions

  ;Language strings
  LangString DESC_SecDummy ${LANG_ENGLISH} "A test section."

  ;Assign language strings to sections
  !insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${SecDummy} $(DESC_SecDummy)
  !insertmacro MUI_FUNCTION_DESCRIPTION_END
 
;--------------------------------
;Uninstaller Section

Section "Uninstall"

  Delete "$INSTDIR\uninstall.exe"

  RMDir /r "$INSTDIR"
  
  !insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuFolder
  
  Delete "$SMPROGRAMS\Little Navmap\*"
  RMDir "$SMPROGRAMS\Little Navmap"

SectionEnd
```

**Comment by albar965** [comment] 2023-02-09 11:34
@decrisp1252 Hi Harvey,
thank you a lot! 
I have to add this to my build chain on Windows. Maybe even for the next update 2.8.9.

**Comment by albar965** [comment] 2023-02-19 12:35
Have to postpone this since more work is needed like adding the program to the Windows unistall programs table and doing automatic uninstallation before installation.
First one seems to be simple like adding 

```
WriteRegStr HKCU "Software\Software\Microsoft\Windows\CurrentVersion\Uninstall\${UninstId}" "DisplayName" "NSIS Test"
WriteRegStr HKCU "Software\Software\Microsoft\Windows\CurrentVersion\Uninstall\${UninstId}" "UninstallString" '"$InstDir\Uninst.exe"'
WriteRegStr HKCU "Software\Software\Microsoft\Windows\CurrentVersion\Uninstall\${UninstId}" "QuietUninstallString" '"$InstDir\Uninst.exe" /S'
```

**Comment by decrisp1252** [comment] 2023-02-20 13:59
No problem, I'll get on it

**Comment by albar965** [comment] 2023-02-20 16:51
Here is an example I found which uses all available registry entries:
https://nsis.sourceforge.io/A_simple_installer_with_start_menu_shortcut_and_uninstaller
Not all needed obviously.

Here is an example with auto-uninstall but this looks complicated using functions and whatnot:
https://nsis.sourceforge.io/Auto-uninstall_old_before_installing_new

**Comment by decrisp1252** [comment] 2023-03-11 14:03
Quick update: sorry I've been really busy with university and other personal issues, but I just wanted to let you know that I'm back working on this and it should be done by the end of today :)

**Comment by decrisp1252** [comment] 2023-03-11 14:46
Here's an updated version! It includes the registry keys for the uninstaller so it shows up in "Add or Remove programs".

Note on lines 34 & 35, I have also included an option for an icon file. This creates the installer with the pretty icon instead of the default NSIS one. It's commented out as I couldn't find a good icon file in the project, but it's definitely worth taking a look at.

Here is the code, it successfully compiled for my version: 

`;NSIS Modern User Interface
;Written by Harvey Walker

;--------------------------------
;Include Modern UI

  !include "MUI2.nsh"

;--------------------------------
;General

  ;Name and file
  Name "Little Navmap"
  OutFile "Install Little Navmap.exe"
  Unicode True

  ;Default installation folder
  InstallDir "$LOCALAPPDATA\Little Navmap"

  ;Request application privileges for Windows
  RequestExecutionLevel user

;--------------------------------
;Variables

  Var StartMenuFolder

;--------------------------------
;Interface Settings

  !define MUI_ABORTWARNING
  !define MUI_FINISHPAGE_NOAUTOCLOSE
  
  ; I could include an icon file here. This will make the logo of the installer, but I couldn't find a good icon in the files. Worth considering!
  ;!define MUI_ICON "F:\NSIS\Little Navmap\icon.ico" 

;--------------------------------
;Pages
  !insertmacro MUI_PAGE_WELCOME
  !insertmacro MUI_PAGE_LICENSE "F:\NSIS\Little Navmap\LICENSE.txt"
  !insertmacro MUI_PAGE_COMPONENTS
  !insertmacro MUI_PAGE_DIRECTORY
  
  !insertmacro MUI_PAGE_STARTMENU Application $StartMenuFolder
  
  !insertmacro MUI_PAGE_INSTFILES
  
  !insertmacro MUI_UNPAGE_CONFIRM
  !insertmacro MUI_UNPAGE_INSTFILES

  !insertmacro MUI_PAGE_FINISH


;--------------------------------
;Languages
 
  !insertmacro MUI_LANGUAGE "English"

;--------------------------------
;Installer Sections

Section "Little Navmap" SecDummy

  SetOutPath "$INSTDIR"
  
  ; ---------- HERE ----------
  File /r "F:\NSIS\Little Navmap\*"
  ; ---------- HERE ----------
  
  ;Create uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ;Registry keys for uninstaller
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Little Navmap" "DisplayName" "Little Navmap"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Little Navmap" "DisplayIcon" "$INSTDIR\littlenavmap.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Little Navmap" "DisplayVersion" "2.8.9"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Little Navmap" "Publisher" "Albar965"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Little Navmap" "UninstallString" "$INSTDIR\uninstall.exe"
  
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
    
    ;Create shortcuts
	CreateDirectory "$SMPROGRAMS\Little Navmap"
    CreateShortcut "$SMPROGRAMS\Little Navmap\Little Navmap.lnk" "$INSTDIR\littlenavmap.exe"
	CreateShortcut "$SMPROGRAMS\Little Navmap\Little Navconnect.lnk" "$INSTDIR\Little Navconnect\littlenavconnect.exe"
    CreateShortcut "$SMPROGRAMS\Little Navmap\Uninstall Little Navmap.lnk" "$INSTDIR\uninstall.exe"
  
  !insertmacro MUI_STARTMENU_WRITE_END

SectionEnd

;--------------------------------
;Descriptions

  ;Language strings
  LangString DESC_SecDummy ${LANG_ENGLISH} "A test section."

  ;Assign language strings to sections
  !insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecDummy} $(DESC_SecDummy)
  !insertmacro MUI_FUNCTION_DESCRIPTION_END
 
;--------------------------------
;Uninstaller Section

Section "Uninstall"

  Delete "$INSTDIR\uninstall.exe"

  RMDir /r "$INSTDIR"
  
  !insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuFolder
  
  Delete "$SMPROGRAMS\Little Navmap\*"
  RMDir "$SMPROGRAMS\Little Navmap"

SectionEnd
`

**Comment by albar965** [comment] 2023-03-12 17:13
A million thanks! I'll add this to the build system for the next release.

**Comment by albar965** [comment] 2023-04-04 11:18
Added skeleton to LNM build process with 5d5310cef73147580b2a78ff452a71d8f88c3622 and added a few more links to the start menu.

I cannot use is yet due to the problem described in https://github.com/albar965/littlenavmap/blob/5d5310cef73147580b2a78ff452a71d8f88c3622/build/win/installer.nsi#L115-L117
This can result in data loss for a user. Selecting a root drive wrongly for installation will wipe the whole drive when uninstalling. Possible solution is [Uninstall only installed files](https://nsis.sourceforge.io/Uninstall_only_installed_files) but too much effort for now.

Nice to have are 
https://github.com/albar965/littlenavmap/blob/5d5310cef73147580b2a78ff452a71d8f88c3622/build/win/installer.nsi#L53 and https://github.com/albar965/littlenavmap/blob/5d5310cef73147580b2a78ff452a71d8f88c3622/build/win/installer.nsi#L109

Alex

**Comment by albar965** [comment] 2023-04-06 11:38
I can have a look at this but more for another version.

**Comment by decrisp1252** [comment] 2023-04-07 15:40
That would definitely be a problem! I'll delve into the documentation and see if I can find a more suitable alternative, as well as add the nice to haves.

**Comment by albar965** [comment] 2023-04-07 15:52
@decrisp1252 Thanks. Appreciate it. Here are a few links I found while doing the research:

Uninstall only installed: https://nsis.sourceforge.io/Uninstall_only_installed_files

Use changlog checkbox for optional program starting: https://stackoverflow.com/questions/30873426/how-to-execute-a-command-from-a-nsis-finish-page#30873769

The first one really looks messy. The whole NSIS language looks like Klingon to me. :slightly_smiling_face: 

Alex

**Comment by decrisp1252** [comment] 2023-04-07 16:09
@albar965 Thanks for the links, I'll have a look :)

Please could you add me to the branch so I can make changes directly to the script? It'd be a lot easier then posting them here! :D

**Comment by albar965** [comment] 2023-04-07 18:24
@decrisp1252 You can create a fork of the branch `release/2.8`, check the fork out to your computer, modify the file and then create a pull request with the changes. This is the normal procedure.

Anyway, I added you to the collaborators list. I think you've got an invitation.

**Comment by decrisp1252** [comment] 2023-04-07 18:35
Ah, sorry I'm relatively new to Github! I'm on holiday at the moment but I'll fork it and work on the updated version as soon as I'm back at my desk.

**Comment by albar965** [comment] 2023-04-07 21:48
Take your time. I can still add the compiled installers later to the release. :+1:

**Comment by decrisp1252** [comment] 2023-04-08 16:01
@albar965 I have managed to implement the option to run littlenavmap no problem. I have also partly coded the option to remove the settings and cache, but I'm not sure where these would be saved. However, that should be easy.

On removing the possibility of accidentally deleting the entire programs folder... that is quite tricky but I think I'm getting the hang of it, but it'll take more effort then I previously appreciated. I haven't pushed anything yet since that's the main issue.

**Comment by albar965** [comment] 2023-04-08 18:28
Configuration and databases are in 
`C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel` 
and there is also a cache folder in 
`C:\Users\YOURUSERNAME\AppData\Local\.marble\data\maps\earth`. 
These can be optionally deleted on uninstall. I guess the log files `C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log` and `abarthel-little_navmap.log.1` are not so important and can remain.

**Comment by decrisp1252** [comment] 2023-04-10 17:04
I'm really sorry but I'm having a really hard time building from the batch file do_all_64.cmd, simply getting this error:
C:\Users\harve\Github\littlenavmap 
C:\Users\harve\Github\littlenavmap\
'""' is not recognized as an internal or external command,
operable program or batch file.
**** ERROR ****
Press any key to continue . . .

I'm completely stuck on how to fix the issue.

**Comment by albar965** [comment] 2023-04-10 18:27
Sorry, forgot to mention this. You need a certain folder structure and a few environment variables set. the `do_all` really needs the full build structure. Do not use this.
Use the script `build_installer.cmd` instead and prepare the build as below. 

Set the environment variables in the cmd/terminal before running `build_installer.cmd`:
- `set APROJECTS=C:\Projects`: Base folder for all projects adapt to what you use. I use `C:\Projects` as an example. Avoid spaces in the path.
- `set WINARCH=win64`: Either `win64` or `win32`.

Create a folder `deploy` in `%APROJECTS` / `C:\Projects`.
Extract the latest LNM 64-bit into the `deploy` folder and create a copy of the extracted folder to `Little Navmap win64`. The result should look like 
- ...
- `C:\Projects\littlenavmap` - checkout from Git branch `release/2.8` with the build scripts.
- ...
- `C:\Projects\deploy\LittleNavmap-win64-2.8.10` - Extracted from latest release. Will be packed into the installer.
- ...
- `C:\Projects\deploy\Little Navmap win64` - Copy of extract. Used to get the version number. **Note the spaces and the missing version in the folder name.**
- ...

Now go to `C:\Projects\littlenavmap\build\win` and  run `build_installer.cmd`.
Hope this helps and do not hesitate to ask if something is wrong.

Alex

**Comment by decrisp1252** [comment] 2023-04-11 11:35
Thanks! I'm glad I managed to sort that out, it makes it a lot easier to test the script.

I'm still working on things but unfortunately I've got uni assignments and an exam coming up so it may have take a backseat. If you'd like, I could add a warning option to the script as a temporary solution to warn people of the danger of selecting the wrong folder to uninstall?

**Comment by albar965** [comment] 2023-04-11 15:19
I would not add a temporary warning. I remember Orbx running into this some time ago. A user installed on his drive, noticed the wrong installation folder and uninstalled. As a result the whole external drive was wiped.

I have no idea why there is no simple solution in NSIS.

As said above: Take your time. Real life assignments and exams more important. I also have to modify Marble to allow add-on map themes outside the installation folder. Without this you cannot add additional map themes if installed to C:\Program Files .

**Comment by decrisp1252** [comment] 2023-05-02 15:02
Hi Alex, I've managed to finish the changes to the installer script. I've opened and linked a pull request :)

**Comment by albar965** [comment] 2023-05-04 19:08
> Hi Alex, this pull request should be more correct, it only includes my changes.

Hi Harvey,
thank you a lot for your work!

Give me some time before I merge. I'd like to finish some other tasks first. 
2.8.11 is still a bit away.
Alex

**Comment by decrisp1252** [comment] 2023-05-04 19:20
No problem, happy to help :) Since the script is now implemented, once you've merged the branches I'll close this issue. If you have more issues with the script or more implementations, feel free to open another one and assign me to it.

**Comment by albar965** [comment] 2023-05-04 19:21
Ok. No problem. :+1:

**Comment by albar965** [comment] 2023-05-27 16:03
Thank you Harvey! I integrated the installer into the workflow but unfortuneately it does not remove all files (only the shortcuts) on uninstall. I tried around but found no easy solution to this.

I'm think NSIS was not a good choice. The [Qt Installation Framework](https://doc.qt.io/qtinstallerframework/ifw-overview.html) removes only installed files per default and uses XML and a readable script language.

Alex

**Comment by harveywalker500** [comment] 2023-05-27 16:11
I agree, it's a massive hassle to use NSIS with its scripts to do anything! 
I'm looking at the installation framework now and it looks fairly easy. I'll make a test and get myself acquainted.

**Comment by albar965** [comment] 2023-05-27 16:13
Ok. That's great. Appreciate it.
Take your time. It does not have to be released with the next 2.8.11. I can always add the installer later.

**Comment by harveywalker500** [comment] 2023-05-27 16:14
Will do :)

It also might be worth opening a discussion for installers? This issue is becoming massive!

**Comment by albar965** [comment] 2023-05-27 19:07
I don't think so. The problem is more to find a good free installer framework.
Qt is mostly free even more for open source projects.

**Comment by albar965** [comment] 2023-05-27 19:09
BTW: I did a few changes in 2.8.11 which allow to install LNM in `C:\Program Files` now. Map themes can now be installed outside the installation folder.

**Comment by albar965** [comment] 2023-06-15 18:18
https://jrsoftware.org/ishelp/
Looks better since QT Installer Framework also removes all files recursively.

**Comment by albar965** [comment] 2023-06-18 19:54
Done using Inno Setup

**Closed by albar965** 2023-06-18 19:54 UTC
Labels: enhancement, requested
