### ISSUE TITLE
Possible memory leak or error?

### ISSUE THREAD

**Issue by Randy97402** [albar965/littlenavmap#360] opened 2018-12-28 00:54 UTC
Hi.  I've just started using LittleNavMap version 2.2.3 and I've noticed that it hangs up, even when many of the features are turned off, it takes several seconds for the map to get dragged, or change it's zoom setting.
I'm nowhere near my memory memory limit or CPU limit and FSX still running at 20-60 frames per second on my Windows 7 Home 64 bit installation.  I put version 2.2.2 back in and it runs just fine, as well as other previous versions.  
Has anyone else seen this issue?

Thanks for all the new features!  It's great to have the correct climb and descent profiles for each of the aircraft. 

(I've been using Little Nav Map since version 1.2.4)

**Comment by albar965** [comment] 2018-12-28 15:32
Hi Randy,
this is not normal Can you send me the log file (`C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log`) of such a session?

Try the usual:
1. Disable anti virus temporarily.
1. Disable firewall temporarily.
1. Install all available Windows redistributable packages. These do not take much space. See [here in the FAQ](https://albar965.github.io/littlenavmap-faq.html#crash) for links.
1. Use the GLOBE data (see [Flight Plan Elevation Profile](https://albar965.gitbooks.io/little-navmap-user-manual/content/en/OPTIONS.html#cache-elevation) )
1. Delete the settings in `C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel` . or better: rename the `ABarthel` directory to something like `ABarthel-backup`
1. Try to use one of the offline map themes

Alex

**Comment by albar965** [comment] 2019-01-02 13:44
Did you try the suggestions (except the firewall)?

I tested LNM on numerous virtual machines and computers and have never seen this. I also get no reports about excessive resource usage.
I'm running this here on virtual machines with 2GB ram without problems.

Just ran a test with network clients, simulator AI and whatnot. LNM stayed below 150 MB and CPU usage in the low single digits.
Alex

![grafik](https://user-images.githubusercontent.com/15254956/50594431-79a02d80-0e94-11e9-971c-f18be1f87519.png)

**Comment by albar965** [comment] 2019-01-07 11:55
Closing since I cannot reproduce this and missing feedback.

**Closed by albar965** 2019-01-07 11:55 UTC

**Comment by Randy97402** [comment] 2019-01-07 12:56
Hi, sorry for the delayed response.  Happy New Year.
I did make sure I had exemptions in both Windows Firewall and Windows Essentials (Windows 7, Home premium, 64bit), but that didn't seem to help much.
I'm having some problem with background process or processes combining to slow my sim to a slideshow about once minute or two, but only for a second or two, then back to normal.  I'm trying to figure it out, but no success yet.
I was trying IOBit system manager, but recently found out it was using more resources than it was freeing for FSX (boxed), so I've removed that from my system now and got a lot of my performance back.  Still tough around places  like KLAX, KSEA, RJTT, EGLL and KJFK, though.
I reverted to your version 2.0.3, since it has much lower cpu usage on my machine than does the new versions with all the new features.  

I use a AMD Ventura 8320 processor, 16 gig ram and FSX on a 500 gig SSD, with addon scenery on a 1 TB Seagate, so no lack of room, but I did find out recently that my old ASUS motherboard only has a 3Gig port for the SSD, not the 6 Gig port I thought it had.  That's my next upgrade, when I can get to it.
Thanks for your help.  Since I fly mainly online, running Discord, ActiveSkyEnvironment and FSX, alongside LittleNavMap, I think your older version is about all I can handle right now.  They keep making Discord bigger and more wasteful of resources, too and thats' not helping either.

    On Wednesday, January 2, 2019, 5:44:39 AM PST, Alexander Barthel <notifications@github.com> wrote:  
 
 
Did you try the suggestions (except the firewall)?

I tested LNM on numerous virtual machines and computers and have never seen this. I also get no reports about excessive resource usage.
I'm running this here on virtual machines with 2GB ram without problems.

Just ran a test with network clients, simulator AI and whatnot. LNM stayed below 150 MB and CPU usage in the low single digits.
Alex

**Comment by albar965** [comment] 2019-01-08 10:55
A (belated) happy new year to you too!

Your computer seems to be far from old and slow but you might have a look at the first chapter here in the manual: [Tips for old and slow Computers](https://albar965.gitbooks.io/little-navmap-user-manual/content/en/APPENDIX.html#tips-for-old-and-slow)
You can also keep the elevation profile closed to avoid the needed background processing.
Also reduce map details.

If this is a general Windows problem you might have a malware infection which eats up CPU time.
Otherwise the only solution is to set up Windows from scratch if nothing helps.

Alex
