### ISSUE TITLE
Am I able to set segment altitude?

### ISSUE THREAD

**Issue by GitPuffy** [albar965/littlenavmap#893] opened 2022-06-12 18:25 UTC
I have put together a flight plan that passes over a mountain range.  I would like to set segment altitudes that clear the minimums but I do not necessary want the entire flight to be at that altitude.  Is there a way to set segments between way points to specific altitudes?

**Comment by albar965** [comment] 2022-06-12 18:37
Sorry, not doable. Duplicate of #587 and  #166

**Closed by albar965** 2022-06-12 18:37 UTC
