### ISSUE TITLE
XPlane Data Sender Idea

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#177] opened 2017-12-02 20:32 UTC
I don't know how its good and if it's support xplane but will be great idea to create option to send to xplane the flight plan in my opinion using Littlenavconnect

**Comment by albar965** [comment] 2017-12-02 21:21
Certainly a useful function which save all the hazzle with saving and loading files.
But it is a duplicate of #35 where I just added X-Plane too.
Closing therefore. Feel free to reopen if needed.

**Closed by albar965** 2017-12-02 21:21 UTC
