### ISSUE TITLE
LittleNavMap may get random hangs (non-responding)

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [albar965/littlenavmap#737] opened 2021-07-15 17:12 UTC
Hi, i have encountered slowdowns with LittleNavMap. When you're scrolling on map or exploring navigational objects (waypoints, airports, beacons etc). Application just hangs as non responding for a while, usually approximately 10 seconds, you have to wait to work with it further. 
I could try to record (but later) video, so you can see it.
It happen even without connecting to simulator, simulator even turned off.
There none high load In task manager - littlenavmap.exe process has consumptions: CPU 12% , HDD is not loaded at all. System monitor also confirm it, there none high HDD activity.
I using 2.6.11 - 2.6.14, all of them has such thing.
OS Windows 10 20H2
Simulator database - Flight Simulator 2020, stock Steam version.
Hardware - Intel i5 10400, 32GB RAM, RTX 2060 Super, SATA3 HDD 1TB WD Blue without any bad sectors, all games (including simulator itself) and software works fine.

**Comment by albar965** [comment] 2021-07-15 21:43
Thanks for the issue. I've got a few reports for this but could not reproduce it yet. It might be related to some user settings because not everybody sees it. Therefore, I need your help.

Can you do the following for me?
- Start LNM
- Note start and end of freeze (including seconds)
- Exit LNM
- Send me the log: `C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log` plus notes when program was frozen

To https://albar965.github.io/contact.html . Maybe I can see something in the log.

If you can find time you can also attach the settings from `C:/Users/YOURUSERNAME/AppData/Roaming/ABarthel`. Database folder `little_navmap_db` is not needed. You can exclude this.

Plenty thanks in advance.

Alex

**Comment by gandalfthewhite19890404** [comment] 2021-07-18 03:37
Sent tests to e-mail yesterday.
Did you recieved them?

**Comment by albar965** [comment] 2021-07-18 10:03
Yes. Got them. And thank you for the files but I'd like to finish some other issues first.
Alex

**Comment by albar965** [comment] 2021-07-19 21:52
Sorry for the delay and thank you very much for the detailed reports. This really helps a lot.

I think the winds aloft download might be an issue. Every time LNM tries to contact the NOMAD site there is a delay of half a minute in your log.

One address from your log is https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.anl&lev_80_m_above_ground=on&lev_150_mb=on&lev_200_mb=on&lev_250_mb=on&lev_300_mb=on&lev_450_mb=on&lev_700_mb=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.20210717%2F00%2Fatmos
for example. This is the winds aloft download. The files downloads within a few seconds if I open this in a browser.

Try the link  above if there are delays on your computer. LNM downloads the wind files within seconds on my computer. 

I'll have a closer look at this with your configuration files tomorrow.

**Comment by gandalfthewhite19890404** [comment] 2021-07-20 02:41
Hi!
What if make some test build without that function for test, or how to turn it off in configuration to test?
How to initiate it by manual - I want to test?
Any thought about implementation in separate thread, as background task or somehow else?

**Comment by albar965** [comment] 2021-07-20 09:22
Turn it off in menu `Weather`. Set `Wind Source` to either `Manual` or ´Disabled`. Set it to simulator if you use X-Plane.

There is no need to implement this in a background thread since this happens only every 30 minutes and is usually a matter of a second.

It seems that something in your network is broken. Either an anti-virus or a firewall limits the access. Maybe DNS issues which delay resolving.

You can also go to LNM options on page `Weather Files` and use the test button of NOAA wind service. See if there is a delay too.

Alex

**Comment by gandalfthewhite19890404** [comment] 2021-07-20 11:38
I'll try to disable Wind Alofts downloading later, I hope - it gonna happen today.
If issue still exist even with disabled wind aloft I'll provide clean logs, videos (if needed).
May I get compiled build with 05406e9 somewhere? I don't have a compiler, so I can't compile it by myself.

**Comment by albar965** [comment] 2021-07-20 14:33
Here is the latest development build for Windows
https://www.magentacloud.de/lnk/trLAgMqO

This contains more changes besides this issue.

But I doubt this will help much. I suppose that the initial connection takes too long. 30 seconds is way too much. Check your network with the link I posted above.

Alex

**Comment by gandalfthewhite19890404** [comment] 2021-07-20 19:17
With latest development build - works awesome! No more hangs!

**Comment by albar965** [comment] 2021-07-21 07:15
Perfect. Thanks for the feedback So I can postpone the multithread thing for a later version.
I suppose it also does not hang with NOAA winds aloft downloads enabled?

**Comment by gandalfthewhite19890404** [comment] 2021-07-21 12:05
I didn't disable it, just run without configuring. All settings was cleared before launch dev version.
So you can get feedback from other users having such issue but with this version.

**Comment by albar965** [comment] 2021-07-21 15:24
Thank you for the feedback and your help again! 
Clearing settings enables NOAA winds aloft download again. This is on per default.

I posted here: https://www.avsim.com/forums/topic/602846-littlenavmap-not-responding/ Similar issue.

**Comment by gandalfthewhite19890404** [comment] 2021-07-21 16:27
Yes, I know it is turned on by default. 
And on 2.6.14 I have got hangs, on development build provided above - works brilliant.

**Closed** 2021-07-24 13:59 UTC
Labels: bug

**Comment by gandalfthewhite19890404** [comment] 2021-07-24 14:10
Can you disable Weather Source like it was done with Wind?
Look at log - it tries to get RWX file (several times) at start and application looks like hung. I can just remove rwx and launch lnm without simulator.
<details>
[2021-07-24 17:04:04.657 DEBUG]: int atools::fs::weather::MetarIndex::readNoaaXplane(QTextStream&, const QString&, bool) "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/15Z.TXT" 5213
[2021-07-24 17:04:04.672 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:04:04.672 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:04:20.294 DEBUG]: int atools::fs::weather::MetarIndex::readNoaaXplane(QTextStream&, const QString&, bool) "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/14Z.TXT" 5256
[2021-07-24 17:04:20.325 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:04:20.325 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:04:55.859 DEBUG]: int atools::fs::weather::MetarIndex::readNoaaXplane(QTextStream&, const QString&, bool) "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/13Z.TXT" 5325
[2021-07-24 17:04:55.984 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:04:55.984 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:05:05.990 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:05:05.990 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:05:15.989 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:05:15.989 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:05:25.989 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:05:25.989 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:05:36.025 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:05:36.026 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
[2021-07-24 17:05:46.013 WARN ]: void atools::util::FileSystemWatcher::pathOrFileChanged() File "D:\\Games\\X-Plane 11\\\\METAR.rwx" does not exist
[2021-07-24 17:05:46.013 WARN ]: cannot watch file "D:\\Games\\X-Plane 11\\\\METAR.rwx"
</details>

**Comment by albar965** [comment] 2021-07-24 15:11
LNM gets the `METAR.rwx` file (completely different thing thank winds aloft) from the X-Plane base folder as set in the scenery library. You can also override this folder in options. Check the path in options on page `Weather Files`. The log messages will be omitted after a while to avoid flooding the log and the file checking has no performance impact.

You can avoid this by disabling simulator weather for info and tooltips in options and by disabling the airport wind symbols in the weather menu.

Anyway, I think the missing option to disable this is inconsistent and confusing. I'll add this.

Also have plans to move the options to weather menu.

Allex
