### ISSUE TITLE
Error opening Little NavMap version 2.6.10

### ISSUE THREAD

**Issue by jfwharton3975** [albar965/littlenavmap#628] opened 2021-03-28 03:12 UTC
I have been getting the following error when I open Little NavMap.
"Error transferring https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t12z.pgrb2.1p00.anl&lev_80_m_above_ground=on&lev_150_mb=on&lev_200_mb=on&lev_250_mb=on&lev_300_mb=on&lev_450_mb=on&lev_700_mb=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.20210327%2F12 - server replied: data file not present" 203
I checked tools, options, weather files and saw the NOAA Wind Service Base URL listed.  A test of that URL is good, so I do not know how to eliminate this error every time I open an existing flight plan or start a new one.

**Comment by cristi-neagu** [comment] 2021-03-28 03:28
Already reported in #623.

**Comment by albar965** [comment] 2021-03-28 10:26
sorry, this is a known problem. See here:
https://www.avsim.com/forums/topic/597802-noaa-wind-download-error/

I'm working on a new release but this will take a few days because there are more changes.

Closing because it is a duplicate of #623 

Alex

**Closed by albar965** 2021-03-28 10:26 UTC
