### ISSUE TITLE
Little Navmap does not release internet connections

### ISSUE THREAD

**Issue by tarpoon** [albar965/littlenavmap#172] opened 2017-11-29 13:10 UTC
Noticed an issue where Little Navmap is kept running overnight. 
What happens is that there are no available browser connections.

1. Keep LN running for 24 hours
2. Open any browser
3. Try to browser to a site
->observe that the browser is not able to connect.

4. Close LN
-> The browser can connect to the internet.

regards,
Tarpoon (TSL)

**Comment by albar965** [comment] 2017-11-29 13:15
Which OS?
Please attach the output of "netstat -ab"

**Comment by tarpoon** [comment] 2017-11-29 16:35
OS: Windows 10 Pro x64.
Not adding my netstat here, you can request it from :)

**Comment by albar965** [comment] 2017-11-29 16:41
Obviously. Fully understand. If you run into this again send it to me by email (see https://albar965.github.io/)

I could not reproduce this in Windows doing a few quick tests. [Procmon](https://technet.microsoft.com/de-de/sysinternals/processmonitor.aspx) from Sysinternals did not show any left over connections after requesting weather, etc.

Maybe it happens when autoconnect is switched on and the remote network end (Little Navconnect) is not available.

Will keep testing.
Thank you for the report.
Alex

**Comment by tarpoon** [comment] 2017-11-29 19:52
I am running LN on the same machine as the sim.

**Comment by albar965** [comment] 2017-11-30 14:24
Sorry to bother you with more questions. What simulator and was the simulator running too? Was LNM connected?

**Comment by tarpoon** [comment] 2017-11-30 21:24
No problem.
Was using P3D V4.
Started LNM, connected to sim. 
Closed Sim. 
Kept LNM running overnight.

This has happened several times. Took a while before I understood that LNM caused it :)

**Comment by albar965** [comment] 2017-12-01 20:04
Please send me the LNM log of such a session. 

I'll check my code but need some time for it. Quite busy now.
Alex

**Comment by albar965** [comment] 2017-12-22 11:16
Closing since no feedback and no log given.

**Closed by albar965** 2017-12-22 11:16 UTC
Labels: bug, waiting for answer
